import type { Metadata } from 'next';
import { GoogleAnalytics } from '@next/third-parties/google';
import { Header, Footer } from '@/components/layout';
import JsonLd from '@/components/JsonLd';
import '@/styles/globals.css';

export const metadata: Metadata = {
  metadataBase: new URL('https://samhwalin.org'),
  title: {
    default: '삼활인 - 세대를 잇는 이야기',
    template: '%s | 삼활인',
  },
  description: '삼활인은 유한한 삶을 기억하며 주어진 삶을 사랑하고 매일의 활력을 되찾는 지역과 세대 간 네트워킹 문화를 만들어갑니다.',
  keywords: ['삼활인', '활서', '세대 교류', '인터뷰 대상자', '생애 기록', '소셜 임팩트'],
  authors: [{ name: '삼활인' }],
  creator: '삼활인',
  icons: {
    icon: [
      { url: '/favicon.ico' },
      { url: '/favicon.svg', type: 'image/svg+xml' },
      { url: '/favicon-96x96.png', sizes: '96x96', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-touch-icon.png' },
    ],
  },
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    url: 'https://samhwalin.org',
    siteName: '삼활인',
    title: '삼활인 - 세대를 잇는 이야기',
    description: '인터뷰 대상자들의 삶을 기록하고, 세대를 연결합니다.',
    // images are dynamically generated by app/opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: '삼활인 - 세대를 잇는 이야기',
    description: '인터뷰 대상자들의 삶을 기록하고, 세대를 연결합니다.',
    // images are dynamically generated by app/opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
  verification: {
    other: {
      'naver-site-verification': '0f658a002565de5dfd454b08a22fc686fe8d144c',
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <head>
        <meta name="theme-color" content="#FFFFFE" />
        <JsonLd />
      </head>
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
      <GoogleAnalytics gaId="G-C1QYFW0EDN" />
    </html>
  );
}
